# Generated by Django 4.2 on 2023-06-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('matricula_nomina', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('rol', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('ejercicio_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('dificultad', models.CharField(max_length=20)),
                ('matricula_nomina', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupo_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('codigo_acceso', models.CharField(max_length=6)),
                ('periodo_ini', models.IntegerField()),
                ('periodo_fin', models.IntegerField()),
                ('Semestre', models.CharField(max_length=12)),
                ('profe_nomina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_Modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('num_intentos', models.IntegerField()),
                ('num_reactivos', models.IntegerField()),
                ('fecha_limite', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('uf_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nombre_uf', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTareaEjercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Sin completar'), ('1', 'Intentado'), ('2', 'Completado')], default='0', max_length=20)),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.ejercicio')),
                ('matricula_nomina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.grupo')),
                ('matricula_nomina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('testCase_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('opcion_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('respuesta', models.BooleanField()),
                ('texto', models.TextField()),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='uf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.uf'),
        ),
        migrations.CreateModel(
            name='EjercicioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.ejercicio')),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('anuncio_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('publicado_el', models.DateField(auto_now_add=True)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programasterApp.grupo')),
            ],
        ),
    ]
